### ISSUE TITLE
changing frequency

### ISSUE THREAD

**Issue by michaelproino** [sparkfun/SparkFun_MiniGen_Arduino_Library#2]
Hi,
Although I try to change frequency with; (changing frequency=20 Hz and keep it constant)

  static float frequency = 20.0;
  unsigned long freqReg = gen.freqCalc(frequency);
  gen.adjustFreq(MiniGen::FREQ0, freqReg);
  delay(100);

My Minigen's output still 150kHz,
Why?

**Comment by mhord** [comment]
Try adding this line before your gen.adjustFreq() line:

gen.FreqAdjustMode(MiniGen::FULL);

There are several settings for the range of the multiplier, and freqCalc() works for the FULL range.

Sorry for the confusion!

**Comment by michaelproino** [comment]
gen.FreqAdjustMode(MiniGen::FULL);

gives an error,

Maybe it can be:
gen.setFreqAdjustMode(MiniGen::FULL);

And,
Must be in setup or loop function?
Thank you for feedback

**Comment by michaelproino** [comment]
Now, my all code is;

#include <SPI.h>
#include <SparkFun_MiniGen.h>

MiniGen gen;

void setup()
{
  gen.reset();
  delay(2000);

  gen.setMode(MiniGen::SQUARE);
  delay(3000);
 
  gen.setMode(MiniGen::SQUARE_2);
  delay(3000);
 
  gen.setMode(MiniGen::TRIANGLE);
  delay(3000);
 
  gen.setMode(MiniGen::SINE);
 
  
}

void loop()
{

  static float frequency = 200.0;
  gen.setFreqAdjustMode(MiniGen::FULL);
  unsigned long freqReg = gen.freqCalc(frequency);
 
  gen.adjustFreq(MiniGen::FREQ0, freqReg);
  delay(100);
  frequency += 200.0;
}


What I mean is getting 20 Hz frequency and increasing it step by step (for example : 10 Hz for every loop)

**Comment by mhord** [comment]
Change the "frequency" value to 20 and the frequency+=200.0 line to frequency += 10.
